# Generated by Django 3.0.3 on 2020-03-04 15:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular genre', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('born_country', models.CharField(default='', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Enter a brief description of the game', max_length=1000)),
                ('cover', models.CharField(default='', max_length=500)),
                ('developer', models.CharField(default='', max_length=150)),
                ('publisher', models.CharField(default='', max_length=150)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('director', models.ManyToManyField(help_text='Select a director for this game', to='resources.Director')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular genre', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('developer', models.CharField(max_length=200)),
                ('generation', models.CharField(choices=[('1st', 'First Generation'), ('2nd', 'Second Generation'), ('3rd', 'Third Generation'), ('4th', 'Fourth Generation'), ('5th', 'Fifth Generation'), ('6th', 'Sixth Generation'), ('7th', 'Seventh Generation'), ('8th', 'Eighth Generation'), ('9th', 'Ninth Generation')], help_text='Video Game Generation', max_length=3)),
                ('media', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('screenshot_1', models.CharField(max_length=500)),
                ('screenshot_2', models.CharField(max_length=500)),
                ('screenshot_3', models.CharField(max_length=500)),
                ('screenshot_4', models.CharField(max_length=500)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='resources.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this game', to='resources.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(help_text='Select a platform for this game', to='resources.Platform'),
        ),
    ]
