# Generated by Django 3.0.3 on 2020-03-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='cpu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platform',
            name='generation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='platform',
            name='media',
            field=models.CharField(max_length=100),
        ),
    ]
